## Prefix for container names; we'll use {container_prefix}-(container_name)
container_prefix: montagu

## Set this flag to true to prevent use of --volumes in the cli to remove
## volumes on stop
protect_data: false

## Docker org for images
repo: vimc

## The name of the docker network that containers will be attached to.
## If you want to proxy Packit to the host, you will need to
## arrange a proxy on this network
network: montagu-network

# Domain where this instance of Montagu will be deployed. E.g. science.montagu.dide.ic.uk
hostname: localhost

## Names of the docker volumes to use
volumes:
  db: db_volume
  burden_estimates: burden_estimate_files
  emails: emails
  templates: template_volume
  guidance: guidance_volume
  static: static_volume
  static_logs: static_logs

api:
  name: montagu-api
  tag: master
db:
  name: montagu-db
  tag: master
  root_user: vimc
  root_password: "changeme"
  migrate:
    name: montagu-migrate
    tag: master
  users:
    api: "apipassword"
    import: "importpassword"
    orderly: "orderlypassword"
    readonly: "readonlypassword"
  protected_tables:
    - gavi_support_level
    - activity_type
    - burden_outcome
    - gender
    - responsibility_set_status
    - impact_outcome
    - gavi_support_level
    - support_type
    - touchstone_status
    - permission
    - role
    - role_permission
proxy:
  name: montagu-reverse-proxy
  tag: vimc-7152
  port_http: 80
  port_https: 443
contrib:
  name: montagu-contrib-portal
  tag: master
admin:
  name: montagu-admin-portal
  tag: master
static:
  name: montagu-static
  tag: master

orderly_web_api_url: http://montagu_orderly_web:8888/api/v2
