## Prefix for container names; we'll use {container_prefix}-(container_name)
container_prefix: montagu

## Set this flag to true to prevent use of --volumes in the cli to remove
## volumes on stop
protect_data: false

## Docker org for images
repo: ghcr.io/vimc

## The name of the docker network that containers will be attached to.
## If you want to proxy Packit to the host, you will need to
## arrange a proxy on this network
network: montagu-network

# Domain where this instance of Montagu will be deployed. E.g. science.montagu.dide.ic.uk
hostname: localhost

## Names of the docker volumes to use
volumes:
  db: db_volume
  burden_estimates: burden_estimate_files
  emails: emails
  templates: template_volume
  guidance: guidance_volume
  mq: mq

api:
  name: montagu-api
  tag: main
  email:
    password: "changeme"
    flow_url: "fakeurl"
  admin:
    name: montagu-cli
    tag: main
db:
  name: montagu-db
  tag: main
  root_user: vimc
  root_password: "changeme"
  migrate:
    name: montagu-migrate
    tag: main
  users:
    api:
      password: "apipassword"
      permissions: all
    import:
      password: "importpassword"
      permissions: all
    orderly:
      password: "orderlypassword"
      permissions: all
    readonly:
      password: "readonlypassword"
      permissions: readonly
    barman:
      password: "barmanpassword"
      option: superuser
    streaming_barman:
      password: "streamingpassword"
      option: replication
  protected_tables:
    - gavi_support_level
    - activity_type
    - burden_outcome
    - gender
    - responsibility_set_status
    - impact_outcome
    - gavi_support_level
    - support_type
    - touchstone_status
    - permission
    - role
    - role_permission
proxy:
  name: montagu-proxy
  tag: main
  port_http: 80
  port_https: 443
  metrics:
    repo: nginx
    name: nginx-prometheus-exporter
    tag: 1.3.0
contrib:
  name: montagu-contrib-portal
  tag: main
admin:
  name: montagu-admin-portal
  tag: main
mq:
  repo: docker.io
  name: redis
  tag: latest
  port: 6379
flower:
  repo: mher
  name: flower
  tag: 0.9.5
  port: 5555
task_queue:
  name: task-queue-worker
  tag: main
  youtrack_token: "faketoken"
  servers:
    montagu:
      user: test.user@example.com
      password: password
    packit:
      url: https://montagu-proxy:443/packit
      disable_certificate_verify: true
    youtrack:
      token: faketoken
    smtp:
      host: smtp.cc.ic.ac.uk
      port: 587
      user: montagu
      password: p@ssword
      from: montagu-notifications@imperial.ac.uk
  tasks:
    diagnostic_reports:
      use_additional_recipients: true
      poll_seconds: 5
      reports:
    archive_folder_contents:
      min_file_age_seconds: 3600

packit_api_url: https://montagu-proxy/packit/api
